name: 惠头条0

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 21,5-15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/heiwoya/lqbz.git ~/lqbz
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/lqbz
          npm install
          npm install cron
          npm install request
      - name: '运行 【惠头条】'
        run: |
          cd ~/lqbz   
          node huitoutiao.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
